using Pre.DelegateGames.Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pre.DelegateGames.Core.Repositories
{
    public class GameRepository
    {
        public IEnumerable<Game> GetGames()
        {
            return new List<Game>
            {
                new Game { Title = "Shadow of the Eldritch", Genre = "RPG", Price = 59.99, Rating = 4.8 },
                new Game { Title = "Neon Drift", Genre = "Racing", Price = 14.99, Rating = 3.5 },
                new Game { Title = "Starbounder", Genre = "Sci-Fi", Price = 0.00, Rating = 4.2 },
                new Game { Title = "Tactical Breach", Genre = "Strategy", Price = 29.99, Rating = 4.0 },
                new Game { Title = "Pixel Farm", Genre = "Simulation", Price = 19.99, Rating = 4.9 },
                new Game { Title = "Cyber Strike", Genre = "Action", Price = 45.00, Rating = 3.2 },
                new Game { Title = "Mystic Forest", Genre = "Adventure", Price = 0.00, Rating = 3.8 },
                new Game { Title = "Final Quest XL", Genre = "RPG", Price = 69.99, Rating = 4.6 },
                new Game { Title = "Speed Demon", Genre = "Racing", Price = 9.99, Rating = 2.9 },
                new Game { Title = "Void Runner", Genre = "Action", Price = 24.50, Rating = 4.1 },
                new Game { Title = "Dungeon Crawler 7", Genre = "RPG", Price = 12.00, Rating = 3.7 },
                new Game { Title = "Space Tycoon", Genre = "Simulation", Price = 34.99, Rating = 4.5 },
                new Game { Title = "Urban Legends", Genre = "Horror", Price = 15.00, Rating = 4.3 },
                new Game { Title = "Grid Iron 2026", Genre = "Sports", Price = 59.99, Rating = 2.1 },
                new Game { Title = "Zen Garden", Genre = "Puzzle", Price = 4.99, Rating = 4.7 },
                new Game { Title = "Mecha Mayhem", Genre = "Action", Price = 49.99, Rating = 4.4 },
                new Game { Title = "Sky Pirates", Genre = "Adventure", Price = 29.99, Rating = 3.9 },
                new Game { Title = "Logic Gate", Genre = "Puzzle", Price = 0.00, Rating = 4.1 },
                new Game { Title = "Velocity X", Genre = "Racing", Price = 19.99, Rating = 3.3 },
                new Game { Title = "Kingdom Fall", Genre = "Strategy", Price = 39.99, Rating = 4.5 },
                new Game { Title = "Bio-Hazard", Genre = "Horror", Price = 59.99, Rating = 4.8 },
                new Game { Title = "Retro Rampage", Genre = "Action", Price = 4.99, Rating = 3.0 },
                new Game { Title = "Galaxy Explorer", Genre = "Sci-Fi", Price = 0.00, Rating = 4.6 },
                new Game { Title = "Chef Simulator", Genre = "Simulation", Price = 14.99, Rating = 4.2 },
                new Game { Title = "Mana Clash", Genre = "RPG", Price = 0.00, Rating = 3.5 },
                new Game { Title = "Deep Sea Terror", Genre = "Horror", Price = 24.99, Rating = 4.0 },
                new Game { Title = "Baller Pro 26", Genre = "Sports", Price = 69.99, Rating = 2.5 },
                new Game { Title = "Infinite Maze", Genre = "Puzzle", Price = 1.99, Rating = 3.8 },
                new Game { Title = "Wasteland Drifter", Genre = "Adventure", Price = 34.99, Rating = 4.3 },
                new Game { Title = "Spellbound", Genre = "RPG", Price = 44.99, Rating = 4.7 },
                new Game { Title = "Titan Duel", Genre = "Action", Price = 0.00, Rating = 3.9 },
                new Game { Title = "City Builder Elite", Genre = "Simulation", Price = 29.99, Rating = 4.1 },
                new Game { Title = "Ghost Hunter", Genre = "Horror", Price = 19.99, Rating = 3.6 },
                new Game { Title = "Mars Colony", Genre = "Sci-Fi", Price = 49.99, Rating = 4.4 },
                new Game { Title = "Quick Chess", Genre = "Strategy", Price = 0.00, Rating = 4.8 },
                new Game { Title = "Rally King", Genre = "Racing", Price = 54.99, Rating = 4.2 },
                new Game { Title = "Hidden Realm", Genre = "Adventure", Price = 12.99, Rating = 3.4 },
                new Game { Title = "Cyber Thief", Genre = "Action", Price = 19.99, Rating = 3.7 },
                new Game { Title = "Dragon Age Legacy", Genre = "RPG", Price = 59.99, Rating = 4.9 },
                new Game { Title = "Mini Golf Madness", Genre = "Sports", Price = 9.99, Rating = 3.1 },
                new Game { Title = "Code Breaker", Genre = "Puzzle", Price = 2.99, Rating = 4.5 },
                new Game { Title = "Star Fighter", Genre = "Sci-Fi", Price = 15.00, Rating = 3.8 },
                new Game { Title = "Hospital Manager", Genre = "Simulation", Price = 24.99, Rating = 4.0 },
                new Game { Title = "Dark Woods", Genre = "Horror", Price = 0.00, Rating = 3.2 },
                new Game { Title = "Battle Tank", Genre = "Action", Price = 9.99, Rating = 3.5 },
                new Game { Title = "Hero Chronicles", Genre = "RPG", Price = 49.99, Rating = 4.6 },
                new Game { Title = "Base Jumper", Genre = "Sports", Price = 0.00, Rating = 2.8 },
                new Game { Title = "World War Tactics", Genre = "Strategy", Price = 39.99, Rating = 4.3 },
                new Game { Title = "Island Survival", Genre = "Adventure", Price = 19.99, Rating = 4.1 },
                new Game { Title = "Neon Biker", Genre = "Racing", Price = 4.99, Rating = 3.9 },
                new Game { Title = "Wizard's Duel", Genre = "RPG", Price = 0.00, Rating = 4.4 },
                new Game { Title = "Nightmare Alley", Genre = "Horror", Price = 14.99, Rating = 3.7 },
                new Game { Title = "Physics Fun", Genre = "Puzzle", Price = 0.00, Rating = 4.7 },
                new Game { Title = "Space Marine", Genre = "Action", Price = 59.99, Rating = 4.5 },
                new Game { Title = "Trucker Sim", Genre = "Simulation", Price = 19.99, Rating = 4.0 },
                new Game { Title = "Sky High Basketball", Genre = "Sports", Price = 29.99, Rating = 3.2 },
                new Game { Title = "Ancient Ruins", Genre = "Adventure", Price = 24.99, Rating = 4.2 },
                new Game { Title = "Super Sudoku", Genre = "Puzzle", Price = 0.00, Rating = 4.9 },
                new Game { Title = "Galactic Conquest", Genre = "Strategy", Price = 44.99, Rating = 4.6 },
                new Game { Title = "Formula One Pro", Genre = "Racing", Price = 69.99, Rating = 4.8 },
                new Game { Title = "Undead Rising", Genre = "Horror", Price = 9.99, Rating = 3.4 },
                new Game { Title = "Cyber Punk Dash", Genre = "Action", Price = 0.00, Rating = 3.1 },
                new Game { Title = "Quest of Valor", Genre = "RPG", Price = 34.99, Rating = 4.3 },
                new Game { Title = "Alien Isolation Zone", Genre = "Sci-Fi", Price = 29.99, Rating = 4.0 },
                new Game { Title = "Flight Sim 2026", Genre = "Simulation", Price = 59.99, Rating = 4.7 },
                new Game { Title = "Table Tennis Champ", Genre = "Sports", Price = 4.99, Rating = 3.5 },
                new Game { Title = "Treasure Map", Genre = "Adventure", Price = 0.00, Rating = 3.9 },
                new Game { Title = "Bridge Builder", Genre = "Puzzle", Price = 14.99, Rating = 4.1 },
                new Game { Title = "Command & Control", Genre = "Strategy", Price = 49.99, Rating = 4.4 },
                new Game { Title = "Drift Master", Genre = "Racing", Price = 19.99, Rating = 3.6 },
                new Game { Title = "Soul Reaver", Genre = "RPG", Price = 54.99, Rating = 4.8 },
                new Game { Title = "The Haunting", Genre = "Horror", Price = 24.99, Rating = 4.2 },
                new Game { Title = "Super Soldier", Genre = "Action", Price = 39.99, Rating = 4.0 },
                new Game { Title = "Star Gate", Genre = "Sci-Fi", Price = 0.00, Rating = 3.7 },
                new Game { Title = "Zoo Keeper", Genre = "Simulation", Price = 19.99, Rating = 4.5 },
                new Game { Title = "Pool Shark", Genre = "Sports", Price = 9.99, Rating = 3.3 },
                new Game { Title = "Cryptic Clues", Genre = "Puzzle", Price = 4.99, Rating = 4.3 },
                new Game { Title = "Lost Empire", Genre = "Adventure", Price = 29.99, Rating = 4.0 },
                new Game { Title = "Total War: Medieval", Genre = "Strategy", Price = 59.99, Rating = 4.7 },
                new Game { Title = "Street Racer", Genre = "Racing", Price = 0.00, Rating = 2.9 },
                new Game { Title = "Grim Reaper", Genre = "Horror", Price = 14.99, Rating = 3.8 },
                new Game { Title = "Shadow Ninja", Genre = "Action", Price = 24.99, Rating = 4.4 },
                new Game { Title = "Paladin's Oath", Genre = "RPG", Price = 44.99, Rating = 4.6 },
                new Game { Title = "Cosmos", Genre = "Sci-Fi", Price = 19.99, Rating = 4.1 },
                new Game { Title = "Farm Life", Genre = "Simulation", Price = 0.00, Rating = 4.2 },
                new Game { Title = "Pro Surfer", Genre = "Sports", Price = 29.99, Rating = 3.0 },
                new Game { Title = "Brain Teaser", Genre = "Puzzle", Price = 1.99, Rating = 4.8 },
                new Game { Title = "Jungle Run", Genre = "Adventure", Price = 0.00, Rating = 3.5 },
                new Game { Title = "Emperor's Decree", Genre = "Strategy", Price = 34.99, Rating = 4.3 },
                new Game { Title = "Moto Cross", Genre = "Racing", Price = 14.99, Rating = 3.9 },
                new Game { Title = "Exorcist", Genre = "Horror", Price = 59.99, Rating = 4.9 },
                new Game { Title = "Laser Tag Online", Genre = "Action", Price = 0.00, Rating = 3.2 },
                new Game { Title = "Dark Souls Remastered", Genre = "RPG", Price = 39.99, Rating = 4.8 },
                new Game { Title = "Deep Space Nine", Genre = "Sci-Fi", Price = 24.99, Rating = 4.0 },
                new Game { Title = "Train Conductor", Genre = "Simulation", Price = 9.99, Rating = 4.1 },
                new Game { Title = "Cricket 2026", Genre = "Sports", Price = 59.99, Rating = 3.4 },
                new Game { Title = "Word Search", Genre = "Puzzle", Price = 0.00, Rating = 4.6 },
                new Game { Title = "Tomb Raider Clone", Genre = "Adventure", Price = 19.99, Rating = 3.7 },
                new Game { Title = "Kingdoms at War", Genre = "Strategy", Price = 0.00, Rating = 4.2 },
                new Game { Title = "Hydro Thunder", Genre = "Racing", Price = 14.99, Rating = 4.0 }
            };
        }
    }
}
